package pojo;
// Generated Oct 7, 2019 8:31:55 PM by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;
import model.DAOAdmin;
import java.util.List;
import model.DAOAdmLogin;
import model.DAOLogin;



/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin  implements java.io.Serializable {


     private Integer idadm;
     private String useradm;
     private String emailadm;
     private String passadm;

    public Admin() {
    }

    public Admin(String useradm, String emailadm, String passadm) {
       this.useradm = useradm;
       this.emailadm = emailadm;
       this.passadm = passadm;       
    }
   
    public Integer getIdadm() {
        return this.idadm;
    }
    
    public void setIdadm(Integer idadm) {
        this.idadm = idadm;
    }
    public String getUseradm() {
        return this.useradm;
    }
    
    public void setUseradm(String useradm) {
        this.useradm = useradm;
    }
    public String getEmailadm() {
        return this.emailadm;
    }
    
    public void setEmailadm(String emailadm) {
        this.emailadm = emailadm;
    }
    public String getPassadm() {
        return this.passadm;
    }
    
    public void setPassadm(String passadm) {
        this.passadm = passadm;
    }


    public void update(){
        DAOAdmin adm = new DAOAdmin();
        //string id = iduse.tostring();
        List<Admin> ladm = adm.getAdmin(idadm);
        if (!ladm.isEmpty()){
            
            adm.updateAdmin(this);
        }
    }
    
    public void save(){
        DAOAdmin adm = new DAOAdmin();
        adm.NewAdmin(this);
        
    }


     public void delete(){
        DAOAdmin adm = new DAOAdmin();
        //string id = idUser
        List<Admin> ladm = adm.getAdmin(idadm);
        if(!ladm.isEmpty()){
            adm.deleteAdmin(idadm);
        }
    }


    public String validasiAdmin(){
    DAOAdmLogin aDao = new DAOAdmLogin();
    List<Admin> ad = aDao.getBy(useradm, emailadm, passadm);
    if(ad != null){
        useradm = ad.get(0).useradm;
        emailadm = ad.get(0).emailadm;
        passadm = ad.get(0).passadm;
        return "adminpage.xhtml";
    }
    return "error";
    }
    
     public void getByID2(){
        DAOAdmin adm = new DAOAdmin();
        List<Admin> lstk = adm.getAdmin(idadm);
        if(!lstk.isEmpty()){
            idadm = lstk.get(0).idadm;
            useradm = lstk.get(0).useradm;
            emailadm = lstk.get(0).emailadm;
            passadm = lstk.get(0).passadm;
        }
       
    }
     
     public List<Admin> getRec(){
        DAOAdmin adm = new DAOAdmin();
        List<Admin> ladm = adm.retrieveAdmin();
        return ladm;
   }
     
     public String idindex2(int a){
         DAOAdmin adm = new DAOAdmin();
         List<Admin> ladm = adm.getAdmin(a);
         if(!ladm.isEmpty()){
             idadm=a;
             useradm = ladm.get(0).useradm;
             emailadm = ladm.get(0).emailadm;
             passadm = ladm.get(0).passadm;
         }
     return "Newadm";
     }

    String idadm(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}


