package pojo;
// Generated Oct 7, 2019 8:31:55 PM by Hibernate Tools 4.3.1

import javax.faces.bean.ManagedBean;
import model.DAOStock;
import java.util.List;



/**
 * Stock generated by hbm2java
 */
@ManagedBean
public class Stock  implements java.io.Serializable {


     private Integer idstk;
     private String namastock;
     private String typestock;
     private String pricestock;
     private String jmlstock;
     private String expstock;

    public Stock() {
    }

    public Stock(String namastock, String typestock, String pricestock, String jmlstock, String expstock) {
       this.namastock = namastock;
       this.typestock = typestock;
       this.pricestock = pricestock;
       this.jmlstock = jmlstock;
       this.expstock = expstock;
    }
   
    public Integer getIdstk() {
        return this.idstk;
    }
    
    public void setIdstk(Integer idstk) {
        this.idstk = idstk;
    }
    public String getNamastock() {
        return this.namastock;
    }
    
    public void setNamastock(String namastock) {
        this.namastock = namastock;
    }
    public String getTypestock() {
        return this.typestock;
    }
    
    public void setTypestock(String typestock) {
        this.typestock = typestock;
    }
    public String getPricestock() {
        return this.pricestock;
    }
    
    public void setPricestock(String pricestock) {
        this.pricestock = pricestock;
    }
    public String getJmlstock() {
        return this.jmlstock;
    }
    
    public void setJmlstock(String jmlstock) {
        this.jmlstock = jmlstock;
    }
    public String getExpstock() {
        return this.expstock;
    }
    
    public void setExpstock(String expstock) {
        this.expstock = expstock;
    }


        public String getbyID(){
        DAOStock stk = new DAOStock();
        List<Stock> lstk = stk.getStock(idstk);
        if(!lstk.isEmpty()){
            idstk = lstk.get(0).idstk;
            namastock = lstk.get(0).namastock;
            typestock = lstk.get(0).typestock;
            pricestock = lstk.get(0).pricestock;
            jmlstock = lstk.get(0).jmlstock;
            expstock = lstk.get(0).expstock;
            return "index";
        }
       return "index";
    }
        
        public void getbyID2(){
        DAOStock stk = new DAOStock();
        List<Stock> lstk = stk.getStock(idstk);
        if(!lstk.isEmpty()){
            idstk = lstk.get(0).idstk;
            namastock = lstk.get(0).namastock;
            typestock = lstk.get(0).typestock;
            pricestock = lstk.get(0).pricestock;
            jmlstock = lstk.get(0).jmlstock;
            expstock = lstk.get(0).expstock;
            
        }
       
    }
    
    public List<Stock> getAllRecords(){
        DAOStock stk = new DAOStock();
        List<Stock> lstk = stk.retrieviewStock();
        return lstk;
    }

    public void update(){
        DAOStock stk = new DAOStock();
        //string id = iduse.tostring();
        List<Stock> lstk = stk.getStock(idstk);
        if (!lstk.isEmpty()){
            
            stk.updateStock(this);
        }
    }
    
    public void save(){
        DAOStock stk = new DAOStock();
        stk.addStok(this);
    }


     public void delete(){
        DAOStock stk = new DAOStock();
        //string id = idUser
        List<Stock> lstk = stk.getStock(idstk);
        if(!lstk.isEmpty()){
            stk.deleteStock(idstk);
        }
    }
    
     public List<Stock> getRec(){
        DAOStock stk = new DAOStock();
        List<Stock> lstk = stk.retrieveStock();
        return lstk;
   }
     
     
     public String idindex(int a){
         DAOStock stk = new DAOStock();
         List<Stock> lstk = stk.getStock(a);
         if(!lstk.isEmpty()){
             idstk=a;
             namastock = lstk.get(0).namastock;
             typestock = lstk.get(0).typestock;
             pricestock = lstk.get(0).pricestock;
             jmlstock = lstk.get(0).jmlstock;
             expstock = lstk.get(0).expstock;                          
             
         }
     return "detail";
     }

        public String idindex2(int a){
         DAOStock stk = new DAOStock();
         List<Stock> lstk = stk.getStock(a);
         if(!lstk.isEmpty()){
             idstk=a;
             namastock = lstk.get(0).namastock;
             typestock = lstk.get(0).typestock;
             pricestock = lstk.get(0).pricestock;
             jmlstock = lstk.get(0).jmlstock;
             expstock = lstk.get(0).expstock;                          
             
         }
     return "edit";
     }

    public String idcart(int a){
         DAOStock stk = new DAOStock();
         List<Stock> lstk = stk.getStock(a);
         if(!lstk.isEmpty()){
             idstk=a;
             namastock = lstk.get(0).namastock;
             typestock = lstk.get(0).typestock;
             pricestock = lstk.get(0).pricestock;
             jmlstock = lstk.get(0).jmlstock;
             expstock = lstk.get(0).expstock;                          
             
         }
     return "cart";
     }    

}


